//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sopro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vertrag
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Typ { get; set; }
        public string Typ_2 { get; set; }
        public System.DateTime Datum { get; set; }
        public System.DateTime Beginn { get; set; }
        public System.DateTime Ende { get; set; }
    }
}
